#!/bin/bash
#SBATCH --job-name=9_gene_overlap_analysis_from_peaks
#SBATCH --account=kubacki.michal
#SBATCH --mem=64GB
#SBATCH --time=6:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kubacki.michal@hsr.it
#SBATCH --error="logs/9_gene_overlap_analysis_from_peaks.err"
#SBATCH --output="logs/9_gene_overlap_analysis_from_peaks.out"

# Documentation:
# This script performs overlap analysis between YAF peaks and SOX2 target genes using pre-annotated peak data.
# It generates Venn diagrams, gene lists for GO analysis, and enrichment statistics.
#
# Input files:
# - COMMON_DATA/sox2_binding.csv: List of SOX2 target genes
# - analysis/8_annotation_and_enrichment/annotation_broad/tables/peak_annotation.csv:
#   Pre-annotated peak file containing gene associations and genomic context.
#   This file is generated by the 6_annotation_and_enrichment.R script.
#
# Output files (in analysis/11_gene_overlap_analysis_from_peaks/):
#   - venn_diagrams.png: Two Venn diagrams showing overlap between YAF and SOX2 genes
#     - One for all genes, one for genes in regulatory regions only
#   - Gene lists for GO analysis:
#     - all_overlapping_genes.txt: Genes found in both YAF and SOX2 sets
#     - all_yaf_only_genes.txt: Genes unique to YAF set
#     - regulatory_overlapping_genes.txt: Genes in regulatory regions found in both sets
#     - regulatory_yaf_only_genes.txt: Genes in regulatory regions unique to YAF
#   - regulatory_regions_enrichment_stats.csv:
#     Statistics comparing YAF concentration values between SOX2 targets and non-targets
#   - regulatory_regions_enrichment_boxplot.png:
#     Visualization of YAF concentration values in regulatory regions

set -e
set -u
set -o pipefail

# Function to log messages with timestamps
log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >&2
}

# Activate conda environment
source /opt/common/tools/ric.cosr/miniconda3/bin/activate
conda activate snakemake

# Define working directory
WORKDIR="/beegfs/scratch/ric.broccoli/kubacki.michal/SRF_H2AK119Ub_cross_V5/SRF_H2AK119Ub/1_iterative_processing"
cd $WORKDIR || { log_message "ERROR: Failed to change to working directory"; exit 1; }

# Define output directory
OUTPUT_DIR="/beegfs/scratch/ric.broccoli/kubacki.michal/SRF_H2AK119Ub_cross_V5/SRF_H2AK119Ub/1_iterative_processing/analysis/11_gene_overlap_analysis_from_peaks"

# Create necessary directories
log_message "Creating output directories..."
mkdir -p "${OUTPUT_DIR}" logs

# Check for required input files
log_message "Checking input files..."
SOX2_FILE="COMMON_DATA/sox2_binding.csv"
PEAK_ANNOTATION_FILE="analysis/8_annotation_and_enrichment/annotation_broad/tables/peak_annotation.csv"

if [[ ! -f "${SOX2_FILE}" ]]; then
    log_message "ERROR: Required file not found: ${SOX2_FILE}"
    exit 1
fi

if [[ ! -f "${PEAK_ANNOTATION_FILE}" ]]; then
    log_message "ERROR: Required file not found: ${PEAK_ANNOTATION_FILE}"
    exit 1
fi

# Run python script for gene overlap analysis
log_message "Running gene overlap analysis..."
python scripts/9_gene_overlap_analysis_from_peaks.py "${OUTPUT_DIR}" "${SOX2_FILE}" "${PEAK_ANNOTATION_FILE}"

log_message "Gene overlap analysis completed"