# Working directory
workdir: "/beegfs/scratch/ric.broccoli/kubacki.michal/SRF_H2AK119Ub_cross_V5/SRF_H2AK119Ub"

# Samples to process
samples:
  - "GFP_1"
  - "GFP_2"
  - "GFP_3"
  - "YAF_1"
  - "YAF_2"
  - "YAF_3"

# Sample conditions
conditions:
  GFP_1: "GFP"
  GFP_2: "GFP"
  GFP_3: "GFP"
  YAF_1: "YAF"
  YAF_2: "YAF"
  YAF_3: "YAF"

# Analysis parameters
params:
  macs2:
    q_value: 0.05
    broad_cutoff: 0.05
    min_length: 500
    max_length: 10000
  trimmomatic:
    min_length: 25
    window_size: 4
    quality: 15
  bowtie2:
    max_fragment: 1000 